worker_count = 4

[nodeconfig]
replica_concurrent_connections = 2
client_concurrent_connections = 2

[clientpoolconfig]
batch_size = 128
clients_per_pool = 1000
batch_timeout_micros = 100
batch_sleep_micros = 100